name: Deploy Flutter Web Octopus with GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["release/staging"]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.7.8'
        
    - name: Clean flutter to be able to generate flutter.js every build
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get
    
    - name: Build serialize data
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build web
      run: |
        echo "APP_ID=${{ secrets.APP_ID }}" >> .env
        echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> .env
        echo "MASTER_KEY=${{ secrets.MASTER_KEY }}" >> .env
        echo "TITLE=${{ secrets.TITLE }}" >> .env
        echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env
        echo "STAGING_PARSE_SERVER_API=${{ secrets.STAGING_PARSE_SERVER_API }}" >> .env
        flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT_TOKEN }} # We use Personal access token instead of Github token since it is set to create a branch container the static page generated from flutter
        publish_dir: build/web
